version: '3.1'
volumes:
  data:
services:
  postgres:
    image: postgres:11.1-alpine
    restart: always
    container_name: meetup_postgres
    working_dir: /application
    volumes:
    - ./data:/var/lib/postgresql/data
    environment:
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=meetup
    ports:
    - '5432:5432'
  redis:
    image: redis:alpine
    ports:
    - '6379:6379'

# docker run --name database -e POSTGRES_PASSWORD=docker -p 5432:5432 -d postgres
# docker run --name redisbarber -p 6379:6379 -d -t redis:alpine



